
GET http://localhost:3000/sites

###
POST http://localhost:3000/sites
Content-Type: application/json

{
    "name": "mase",
    "description": "kese",
    "imageURL": "shese"
}

###

DELETE http://localhost:3000/sites/61c364a6e4f8f74a2f8d2573


### 

PATCH http://localhost:3000/sites/61c423c324114d090b6e5730
Content-Type: application/json

{
    "name": "Johny",
    "description": "ye",
    "imageURL": "se"
}

###

DELETE  http://localhost:3000/sites
