
GET http://localhost:3000/sites

###
POST http://localhost:3000/sites
Content-Type: application/json

{
    "name": "Konoha",
    "description": "yese",
    "imageURL": "yese"
}

###

DELETE http://localhost:3000/sites/61bf804e342927febfdc5f49


### 

PATCH http://localhost:3000/sites/61bb6f939897bf612a396dfb
Content-Type: application/json

{
    "name": "John",
    "description": "ye",
    "imageURL": "se"
}
